### PR TITLE
Make cpu60 42 lines for obvious reasons

### PR DESCRIPTION
**Pull request by oldaccountarchived**
42 is the answer to life, the universe, and everything and therefore is preferred over 60, a number we are clinging onto because Sumerians said it was a good idea.

### CODE REVIEW

**Comment by liamjack** [comment]
:+1:

**Comment by smithjessk** [comment]
:+1:

**Comment by yorickdewid** [comment]
:+1:

**Comment by wkoszek** [comment]
Jacob,

As much as I understand your motivation behind 42, the changes would force me to rebrand the project and do other things which I didn't want (bracket removal)

Feel free to make `cpu42` and link it to `cpu60` as a predecessor.

Thanks!

**Pull request closed without merging**
